apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  namespace: manoj
  labels:
    env: dev
    user: manoj
spec:
  containers:
  - name: c1
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root123
    - name: MYSQL_DATABASE
      value: allianzdb
